
export enum AppStep {
  IDLE,
  REQUESTING_PERMISSION,
  PERMISSION_DENIED,
  RECORDING_ORIGINAL,
  PROCESSING_ORIGINAL,
  PLAYING_REVERSED_ORIGINAL,
  RECORDING_IMITATION,
  PROCESSING_IMITATION,
  PLAYING_REVERSED_IMITATION,
}
